// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: event.proto

package proto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind      uint32               `protobuf:"varint,1,opt,name=Kind,proto3" json:"Kind,omitempty"`
	When      *timestamp.Timestamp `protobuf:"bytes,2,opt,name=When,proto3" json:"When,omitempty"`
	Mask      uint32               `protobuf:"varint,3,opt,name=Mask,proto3" json:"Mask,omitempty"`
	Reserved  uint32               `protobuf:"varint,4,opt,name=Reserved,proto3" json:"Reserved,omitempty"`
	Keycode   uint32               `protobuf:"varint,5,opt,name=Keycode,proto3" json:"Keycode,omitempty"`
	Rawcode   uint32               `protobuf:"varint,6,opt,name=Rawcode,proto3" json:"Rawcode,omitempty"`
	Keychar   int32                `protobuf:"varint,7,opt,name=Keychar,proto3" json:"Keychar,omitempty"`
	Button    uint32               `protobuf:"varint,8,opt,name=Button,proto3" json:"Button,omitempty"`
	Clicks    uint32               `protobuf:"varint,9,opt,name=Clicks,proto3" json:"Clicks,omitempty"`
	X         int32                `protobuf:"varint,10,opt,name=X,proto3" json:"X,omitempty"`
	Y         int32                `protobuf:"varint,11,opt,name=Y,proto3" json:"Y,omitempty"`
	Amount    uint32               `protobuf:"varint,12,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Rotation  int32                `protobuf:"varint,13,opt,name=Rotation,proto3" json:"Rotation,omitempty"`
	Direction uint32               `protobuf:"varint,14,opt,name=Direction,proto3" json:"Direction,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Event) GetWhen() *timestamp.Timestamp {
	if x != nil {
		return x.When
	}
	return nil
}

func (x *Event) GetMask() uint32 {
	if x != nil {
		return x.Mask
	}
	return 0
}

func (x *Event) GetReserved() uint32 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

func (x *Event) GetKeycode() uint32 {
	if x != nil {
		return x.Keycode
	}
	return 0
}

func (x *Event) GetRawcode() uint32 {
	if x != nil {
		return x.Rawcode
	}
	return 0
}

func (x *Event) GetKeychar() int32 {
	if x != nil {
		return x.Keychar
	}
	return 0
}

func (x *Event) GetButton() uint32 {
	if x != nil {
		return x.Button
	}
	return 0
}

func (x *Event) GetClicks() uint32 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *Event) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Event) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Event) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Event) GetRotation() int32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *Event) GetDirection() uint32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

var File_event_proto protoreflect.FileDescriptor

var file_event_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d,
	0x61, 0x69, 0x6e, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe7, 0x02, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x4b, 0x69,
	0x6e, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x57, 0x68, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x57, 0x68,
	0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x4b, 0x65, 0x79, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x52, 0x61, 0x77, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x52,
	0x61, 0x77, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x63, 0x68, 0x61,
	0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4b, 0x65, 0x79, 0x63, 0x68, 0x61, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x63,
	0x6b, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x73,
	0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x58, 0x12, 0x0c,
	0x0a, 0x01, 0x59, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x59, 0x12, 0x16, 0x0a, 0x06,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1c, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x09,
	0x5a, 0x07, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData = file_event_proto_rawDesc
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_event_proto_rawDescData)
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_event_proto_goTypes = []interface{}{
	(*Event)(nil),               // 0: main.Event
	(*timestamp.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_event_proto_depIdxs = []int32{
	1, // 0: main.Event.When:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_rawDesc = nil
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
